### ISSUE TITLE
$error:=cURL_FTP_Delete - Returns 21

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl-ftp#1]
latest 2.9 carbon branch,
4D v17r2 32 Bit (final) macOS 10.12.6

$error:=cURL_FTP_Delete return error 21

C_OBJECT($options)
OB SET($options;\
"URL";"ftp://ftp.node.de/test.txt";\
"USERNAME";"myuser";\
"PASSWORD";"mypass")

$error:=cURL_FTP_Delete (JSON Stringify($options)) // returns 21

Thanks Armin

//cURL FTP version 2.9, Copyright 2018 miyako

With CURL V2 carbon plugin it works fine

		OB SET($optiondel;\
		"URL";"ftp://ftp.node.de/";\
		"USERNAME";"myuser";\
		"QUOTE";New collection("DELE test.txt");\
		"PASSWORD";"mypass")
		 
		$error:=cURL (JSON Stringify($optiondel);$request;$response)

**Comment by miyako** [comment]
I have made several changes in 2.10 in the hope to solve this issue.

1. use POSTQUOTE for sftp, QUOTE for ftp.
2. remove file name from the URL in case of DELE/rm
3. prepend / to path in case of sftp+rm which expects an absolute path

**Comment by ArminDeeg** [comment]
![ftp_del](https://user-images.githubusercontent.com/6436037/49017916-55ad4600-f18a-11e8-8cae-3cfd3b3a53be.png)
![sftp_del](https://user-images.githubusercontent.com/6436037/49017922-58a83680-f18a-11e8-8cef-ac8a4e2bc241.png)

**SUCCESS**

Tried 2.10 carbon and both FTP Delete and SFTP Delete works

Thanks
