### ISSUE TITLE
Stop callback method

### ISSUE THREAD

**Issue by rere3091** [miyako/4d-plugin-curl-ftp#10]
Hi Miyako,

I use your plugin for to appear a progress bar with the command Progress New, in this command we can set a button to close the progress bar.

So in the callback I can detect if the user click on this button, but I can't stop the procedure and the callback method is call each time until the download is complete...

How can I abort the callback ?

Thanks.

**Comment by miyako** [comment]
have you tried passing `True` to `$0` in the callback method?

**Comment by rere3091** [comment]
Ok it work perfetly, thank's you :)
