### ISSUE TITLE
SFTP Connection not closed after Send File

### ISSUE THREAD

**Issue by powerwerk** [miyako/4d-plugin-curl-ftp#14]
Hello,
thank you for this plugin.

I use it to send a file to a sftp server
The file can be uploaded successfully, but the owner of the server complains, that I do not log out after send,
and his software will not use my uploaded file until I log out from the server.

Are there any options I could use to force log out ?

Mike.

I use the following code:
////////////
$username:=$1
$password:=$2
$url:=$3
$filepath:=$4

C_OBJECT($options)
OB SET($options; "URL"; "sftp://"+$url)
OB SET($options; "USERNAME"; $username)
OB SET($options; "PASSWORD"; $password)

$createMissingDir:=1

$error:=cURL_FTP_Send(JSON Stringify($options); $filepath; $createMissingDir)
///////////

**Comment by miyako** [comment]
maybe [`CURLOPT_FORBID_REUSE`](https://curl.se/libcurl/c/CURLOPT_FORBID_REUSE.html)

for the plugin the option name would be `FORBID_REUSE`
