### ISSUE TITLE
sftp returns error 1 

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl-ftp#2]
Latest 2.9 carbon branch
4D v17r2 32 final 32 Bit, macOS 10.12.6

sftp:// returns error 1, ftp:// works fine like expected
Do I miss some options to set ? (old version with libcurl 7.57 works fine but slow)
`C_OBJECT($options)

$path:=System folder(Desktop)+"test.png"

OB SET($options;\
"URL";"sftp://ftp.node.de/test.png";\
"USERNAME";"myuser";\
"PASSWORD";"mypass")
$createMissingDir:=1
$error:=cURL_FTP_Send (JSON Stringify($options);$path;$createMissingDir) //returns error 1`

Thanks Armin

//cURL FTP version 2.9, Copyright 2018 miyako

With CURL v2 carbon plugin it works fine

	OB SET($options;\
	"URL";"sftp://ftp.node.de/test.png";\
	"USERNAME";"myuser";\
	"UPLOAD";1;\
	"UPLOAD_BUFFERSIZE";1024000;\
	"PASSWORD";"mypass")

	DOCUMENT TO BLOB($path;$request)
	$error:=cURL (JSON Stringify($options);$request;$response)

**Comment by miyako** [comment]
error #1 is unsupported protocol. I must have built it with the wrong libcurl

**Comment by miyako** [comment]
should be fixed in https://github.com/miyako/4d-plugin-curl-ftp/releases/tag/2.9.1-carbon

**Comment by miyako** [comment]
for the record, master 2.9 didn't have this problem

**Comment by ArminDeeg** [comment]
![sftp](https://user-images.githubusercontent.com/6436037/49017408-13cfd000-f189-11e8-966b-d7958eebc5d0.png)
![ftp](https://user-images.githubusercontent.com/6436037/49017417-16cac080-f189-11e8-9adf-745d98ed4959.png)

now FTP and SFTP does not work, FTP Error: 3 and SFTP Error: 79

![bildschirmfoto 2018-11-26 um 14 37 52](https://user-images.githubusercontent.com/6436037/49017438-23e7af80-f189-11e8-9b5d-434afb83b947.png)

**Comment by ArminDeeg** [comment]
**Success**
With 2.9.1 carbon, both FTP Send, SFTP Send, FTP Delete and SFTP Delete works fine
It seems that the 2.10 has new problems

**Comment by miyako** [comment]
2.10 regression must be a rm/DELE side effect. just posted 2.11

**Comment by ArminDeeg** [comment]
Success

2.11 carbon works fine on mac
