### ISSUE TITLE
cURL_FTP_Receive -> error 3

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-curl-ftp#3]
with 2.11 carbon 32Bit 4D v17r2

![bildschirmfoto 2018-11-26 um 18 39 40](https://user-images.githubusercontent.com/6436037/49031605-bf3d4c80-f1aa-11e8-9324-e65ca9e515e6.png)

URL Malformat

**Comment by miyako** [comment]
#3 is because you didn't **JSON stringify** and an empty JSON was passed.

that said, I did get #23 (CURLE_WRITE_ERROR)

**Comment by miyako** [comment]
no problems if $path is a file, not directory.

**Comment by miyako** [comment]
are you sure the code worked before?

**Comment by ArminDeeg** [comment]
My fault, sorry for the noise

Forgot json stringify and full path

Thanks Armin
