### ISSUE TITLE
cURL_FTP_GetFileInfo produces strange result

### ISSUE THREAD

**Issue by scopie2** [miyako/4d-plugin-curl-ftp#4]
Using version 2.13. Running the below code on a Mac zipped application located on a remote sftp server

$error:=cURL_FTP_GetFileInfo (JSON Stringify($options);$info)
alert($info)

produces the below alert box:

![image](https://user-images.githubusercontent.com/47672751/53044010-a86f6480-343e-11e9-9bd5-db8110e71a81.png)

The "date" can be extracted and is usable but the size is not usable.

Is this a bug or is there something unique about a zipped Mac app? The size would be nice to use for a progress bar but is not essential.

**Comment by miyako** [comment]
it's a bug; jsoncpp is implicitly converting string to bool;

**Comment by miyako** [comment]
should be fixed in 2.14
