### ISSUE TITLE
getFileInfo

### ISSUE THREAD

**Issue by scopie2** [miyako/4d-plugin-curl-ftp#5]
v2.14

$error:=cURL_FTP_GetFileInfo (JSON Stringify($options);$info)
ALERT($info)

now produces this:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/47672751/53143435-cc20d080-354c-11e9-9e49-4a5cf03983f8.png">

file size is ~153MB

**Comment by miyako** [comment]
it might be URL specific

```
$options:=New object
$options.URL:="ftp://ftp.4d.com/PRODUCTS/4D/Archives/4D_v11_SQL/Mac/Standalone/4D_v11_SQL_Release_9_US.dmg"

$error:=cURL_FTP_GetFileInfo (JSON Stringify($options);$info)

ALERT($info)
```

<img width="510" alt="2019-02-21 13 39 03" src="https://user-images.githubusercontent.com/1725068/53144072-130ad680-35de-11e9-8088-db7e76c3a4c2.png">

**Comment by scopie2** [comment]
I'm using sftp.  Here is the URL

"URL";"sftp://y16-7.macminivault.com/Volumes/Macintosh HD/Users/coninpro/ConInPro.zip";\

If there is no issue with these, then there is something about the zipped merged 4D application file that causes the problem.

I could try creating the $object with the different syntax you use now vs. the examples

**Comment by miyako** [comment]
SFTP doesn't invoke CURLOPT_HEADERFUNCTION

I've changed the logic to retrieve file size, please try 2.15

**Comment by scopie2** [comment]
Works great!

Thank You
