### ISSUE TITLE
cURL_FTP_Delete returns error 2 in  2.16

### ISSUE THREAD

**Issue by uschwitzgebel** [miyako/4d-plugin-curl-ftp#6]
Hello MIYAKO,
(sorry for the double post in 4D Forum - new to github)

we have an issue with SFTP, newest version 2.16, OSX Sierra, 17.1/ 64 Bit and error 2 when calling cURL_FTP_Delete or cURL_FTP_Rename  

**Found out that in Version 2.12 it is still working !!**

OB SET($options;\
"URL";"sftp://server";\
"USERNAME";"myname";\
"PASSWORD";"mypw")

$error:=cURL_FTP_GetDirList (JSON Stringify($options);$list)
$error:=cURL_FTP_PrintDir (JSON Stringify($options);$list)

**working as expected.**

OB SET($options;\
"URL";"sftp://server/file";\
"USERNAME";"myname";\
"PASSWORD";"mypw")

$path is set

$error:=cURL_FTP_Receive (JSON Stringify($options);$path)

**working as expected.**

error:=cURL_FTP_Delete (JSON Stringify($options))

and

$error:=cURL_FTP_Rename (JSON Stringify($options);$name)

**throwing error 2**

Thanks alot for your continuous work !

**Comment by miyako** [comment]
please try 2.17

**Comment by uschwitzgebel** [comment]
cURL_FTP_Delete and cURL_FTP_Rename  are now working as expected.
Thanks.
