### ISSUE TITLE
cURL_FTP_GetFileInfo date issue

### ISSUE THREAD

**Issue by scopie2** [miyako/4d-plugin-curl-ftp#7]
When I use **cURL_FTP_GetFileInfo** here in the USA I think it's giving me a Japan date.

For example, now it's 19:25, 6 May 2019 at my location. I uploaded a file just now to a USA Mac server. When I do "get info" on that file on the Server it says "Created May 6, 2019" and "Modified May 6, 2019". When **cURL_FTP_GetFileInfo** looked at that file just now it says the "date" is May 7, 2019 = the date in Japan. I could correct this by subtracting one day but if it's Japan time that will not always be correct. If it's always one day ahead, that's easy to fix on this end.

Do I have to create a method to figure out the local time zone vs. Japan time or is there an easier way?

**Comment by miyako** [comment]
the source reads,

``strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%SZ", &ts);``

it is common to use UTC (GMT) in the internet world.

**Comment by miyako** [comment]
so it would be quite wrong to subtract one day.
