### ISSUE TITLE
curl-ftp

### ISSUE THREAD

**Issue by joerg-eyring** [miyako/4d-plugin-curl-ftp#8]
Hi Keisuke,

we're having troubles to move (= rename) a file on the ftp server using cURL_FTP_Rename. Whenever the file to be moved (= renamed) is located within a subdirectory, everything is OK. But as soon as the file is located in the root directory of the ftp server, moving (= renaming) fails with cURL error 21.

We're using the following code:

C_OBJECT($options)

OB SET($options;\
"URL";"ftp://ftp.example.com/test.zip";\
"USERNAME";"user";\
"PASSWORD";"pass")

$name:="/b/test.zip"

$error:=cURL_FTP_Rename (JSON Stringify($options);$name)

As soon as the file resides in a subdirectory of the ftp server, it works. i.e:

OB SET($options;\
"URL";"ftp://ftp.example.com/a/test.zip";\
"USERNAME";"user";\
"PASSWORD";"pass")

$name:="/b/test.zip"

$error:=cURL_FTP_Rename (JSON Stringify($options);$name)

We've been trying several syntax forms -> no success.

Any hints what we're doing wrong?

BTW: There's a small glitch in the docs. The full pathname of the "rename to" path has to begin with a "/", otherwise the rename won't work either.

Regards, Jörg

**Comment by joerg-eyring** [comment]
Hi, just an additional information: Doing the same with SFTP works fine.
Jörg

**Comment by miyako** [comment]
the code for SFTP vs FTP are completely different. recent bugs are almost always caused by fixing one, breaking the other.

today I fixed cURL_FTP_Rename on the **FTP** side, so that "rename to" can be a relative path (no ``/`` prefix) or absolute path (with ``/`` prefix) Note: libcurl/FTP supports relative path. libcurl SFTP seems to demand absolute path.

I have removed the original code that added a ``/`` prefix for SFTP, for better control. however this may result in consistent behaviour across protocol (in FTP, "/name" refers to the root, "name" refers to the current directory; in SFTP, "/name" refers to the current directory, I have no idea where "name" will reference)

thank you for testing both.

**Comment by joerg-eyring** [comment]
Hi Keisuke, thanks for version 3.9.
FTP is working now, I can rename (= move) files from the root directory to somewhere else.
But - as you mentioned - SFTP is completely broken now. Neither moving from one subdirectory to another nor moving a file from root to somewhere else is working…
Probably it's the version: We've been using curl-ftp 2.18 (carbon branch) up to now. For FTP it wasn't possible to move files from the root to somewhere else in this version. SFTP was completely functional.
Now in 3.9 FTP is working as expected, SFTP isn't working at all (always error 21). We didn't test earlier non-carbon-versions of curl-ftp.
Regards, Jörg

**Comment by miyako** [comment]
Hello, "completely broken" is not exactly technical. 
what if you add a "/" prefix to the "new name" for SFTP?

**Comment by joerg-eyring** [comment]
Sorry for not being precise - you're right ;-)
With "completely broken" I only mean the call cURL_FTP_Rename with SFTP at the moment.

The following constructs don't work with 3.9 - they all yield cURL error 21:
…
URL";"sftp://ftp.example.com/test.zip";\ //moving from root to root (= rename)
$name:="test_copy.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/test.zip";\ //moving from root to root (= rename)
$name:="/test_copy.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/test.zip";\ //moving from root to subdir
$name:="a/test.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/test.zip";\ //moving from root to subdir
$name:="/a/test.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/a/test.zip";\ //moving from subdir to root
$name:="test.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/a/test.zip";\ //moving from subdir to root
$name:="/test.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/a/test.zip";\ //moving from subdir to subdir
$name:="b/test.zip" //worked with cURL-FTP-Plugin 2.18
…
…
URL";"sftp://ftp.example.com/a/test.zip";\ //moving from subdir to subdir
$name:="/b/test.zip" //worked with cURL-FTP-Plugin 2.18
…

The file to be moved/renamed does not exist at the destination, the folder hierarchy is existent.
Regards, Jörg

**Comment by miyako** [comment]
like I said, the code has evolved significantly, so I can't bring back the code from 2.18 or whatever. 

I appreciate your set of unit test codes, all I need now is an SFTP for testing purposes... wink wink

**Comment by joerg-eyring** [comment]
Hi Keisuke,

please see: https://forums.4d.com/Post/FR/31497545/1/31509027#31509027

Quote: "…To reproduce, you must have access to an SFTP server […]. An easy way - that's what I did - is to setup Rumpus for macOS. It gives you a trial period for a couple of weeks and after a few minutes the SFTP server was up and running.…"

Get it here: https://www.maxum.com/Rumpus/

Regards, Jörg

**Comment by miyako** [comment]
I did that for my last computer but right now I am not prepared to install Rumpus on my computer which contains much baggage already.

3.9.1 will have to be the last edit for considerable time. hope it helps.

**Comment by miyako** [comment]
by the way, it seem normal that the status code for a successful rename should be "remote file does not exist" (because it moved)

**Comment by miyako** [comment]
appreciate it if you could test 3.9.x for sftp rename

**Comment by joerg-eyring** [comment]
So your advice is to always masking out curl error 78 (CURLE_REMOTE_FILE_NOT_FOUND) in case of an sftp rename? And what, if the remote file doesn't exist on the ftp Server? cURL-Plugin returns error 21, what definitely isn't an appropriate result code.

Comparing the function "cURL_FTP_Rename" in curl ftp 2.18 with curl ftp 3.9.x I see you're using curl_easy_setopt(curl, CURLOPT_QUOTE, h) (version 3.9.x) while in version 2.18 you were using curl_easy_setopt(curl, CURLOPT_POSTQUOTE, h).

In version 2.18 sftp rename worked properly returning curl error 0 for success or curl error 78 when the file to be renamed didn't exist.

Just for fun I rebuilt cURL-Plugin 3.9.x with this modification and now sftp rename is working properly and as expected: returning 0 for success and 78 when the file to be renamed was not found on the ftp server.

Regards, Jörg

BTW: all scenarios mentioned above for an sftp rename seem to work now, when using CURLOPT_POSTQUOTE even with correct return codes ;-)

**Comment by miyako** [comment]
honestly, I don't have an opinion on that. 
I don't use this plugin myself,
and I don't have a deep understanding of how quote or post-quote is supposed to work.
if you believe you know how to improve the plugin, 
could you be more specific,  
that is, the exact diff for which file in which repository should be modified.
I can not work with information like 

> Comparing the function "cURL_FTP_Rename" in curl ftp 2.18 with curl ftp 3.9.x I see you're using curl_easy_setopt(curl, CURLOPT_QUOTE, h) (version 3.9.x) while in version 2.18 you were using curl_easy_setopt(curl, CURLOPT_POSTQUOTE, h).

**Comment by joerg-eyring** [comment]
According to the description of CURLOPT_QUOTE on curl.haxx.se my understanding is that CURLOPT_QUOTE is issued BEFORE any transfer, while CURLOPT_POSTQUOTE is issued AFTER the transfer. Since renaming doesn't involve any transfer, CURLOPT_POSTQUOTE should be the right option - and that's what you did in your plugin version 2.18 and what's working correctly.

[cURL_FTP_Rename_Change_From.txt.zip](https://github.com/miyako/4d-plugin-curl-ftp/files/4213989/cURL_FTP_Rename_Change_From.txt.zip)

[cURL_FTP_Rename_Change_To.txt.zip](https://github.com/miyako/4d-plugin-curl-ftp/files/4213990/cURL_FTP_Rename_Change_To.txt.zip)

Regards, Jörg

**Comment by miyako** [comment]
is this good?

https://github.com/miyako/4d-plugin-curl-ftp/releases/tag/3.9.3.v18
https://github.com/miyako/4d-plugin-curl-ftp/releases/tag/3.9.3.v17

**Comment by joerg-eyring** [comment]
Thanks, haven's tested thoroughly, but sftp rename with v17 plugin on macOS now works properly :-)

**Comment by miyako** [comment]
good to know!
