### ISSUE TITLE
Possible to send sftp command to server

### ISSUE THREAD

**Issue by nilskoll** [miyako/4d-plugin-curl-ftp#9]
I would like to send a "chmod" sftp command to change permission on a file that was transferred.
Is there a way to access the "-Q/--quote" option in curl with this plugin?

**Comment by miyako** [comment]
no, the plugin is intentionally simple and specific by design. 

you might want to look into the other generic plugin 

https://github.com/miyako/4d-plugin-curl-v2

**Comment by nilskoll** [comment]
OK, thanks for the quick response!
I solved my issue serverside, but thanks for the pointer to the generic curl.
